[package]
name = "recurse"
version = "0.0.1"
authors = ["Chris Simpkins <git.simpkins@gmail.com>"]
description = "Recursive directory traversal file management tool"
edition = "2018"


[dependencies]
walkdir = "2.3.1"
structopt = "0.3"
anyhow = "1.0"
# rayon = "1.3"
regex = "1.3"
colored = "1.9"