[package]
name = "shot"
version = "0.0.1"
authors = ["Chris Simpkins <git.simpkins@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
structopt = "0.3"
anyhow = "1.0"