on: [push, pull_request]

name: Rustfmt check

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Run rustfmt check
        run: |
          rustup component add rustfmt
          cargo fmt --version
          cargo fmt -- --check || (echo "Please reformat your code with 'cargo fmt' (version $(cargo fmt --version))"; false)
